import type { Dataset } from "./types"

export const mockDatasets: Dataset[] = [
  {
    id: "1",
    name: "Financial Market Trends 2023",
    description:
      "Comprehensive dataset of global financial markets including stocks, bonds, and cryptocurrencies with historical data and predictive indicators.",
    price: 299,
    owner: "FinanceAI Labs",
    category: "Finance",
    dataType: "Time Series",
    size: "2.4 GB",
    downloads: 1245,
    popularity: 98,
    verified: true,
    createdAt: "2023-11-15",
    previewImage: "/placeholder.svg?height=400&width=600&text=Financial+Data",
    recommended: true,
    recommendationReason:
      "High-quality financial data with excellent predictive indicators that match your portfolio analysis interests.",
    matchScore: "95",
  },
  {
    id: "2",
    name: "Healthcare Patient Records (Anonymized)",
    description:
      "Anonymized patient records for research purposes, including medical history, treatments, and outcomes across various conditions and demographics.",
    price: 499,
    owner: "MedData Research",
    category: "Healthcare",
    dataType: "Structured",
    size: "5.7 GB",
    downloads: 876,
    popularity: 92,
    verified: true,
    createdAt: "2023-10-05",
    previewImage: "/placeholder.svg?height=400&width=600&text=Healthcare+Data",
    recommended: true,
    recommendationReason:
      "Matches your previous healthcare analytics projects with comprehensive patient journey data.",
    matchScore: "98",
  },
  {
    id: "3",
    name: "E-commerce Customer Behavior",
    description:
      "Detailed customer behavior data from major e-commerce platforms, including browsing patterns, purchase history, and product interactions.",
    price: 349,
    owner: "RetailInsights",
    category: "E-commerce",
    dataType: "Structured",
    size: "3.2 GB",
    downloads: 1532,
    popularity: 97,
    verified: true,
    createdAt: "2023-12-01",
    previewImage: "/placeholder.svg?height=400&width=600&text=E-commerce+Data",
  },
  {
    id: "4",
    name: "Social Media Sentiment Analysis",
    description:
      "Comprehensive dataset of social media posts with sentiment analysis, demographic information, and engagement metrics across multiple platforms.",
    price: 199,
    owner: "SocialMetrics",
    category: "Social Media",
    dataType: "Text",
    size: "1.8 GB",
    downloads: 2145,
    popularity: 94,
    verified: true,
    createdAt: "2023-11-20",
    previewImage: "/placeholder.svg?height=400&width=600&text=Social+Media+Data",
  },
  {
    id: "5",
    name: "IoT Sensor Readings - Smart Cities",
    description:
      "Real-time and historical sensor data from smart city deployments, including traffic, air quality, noise levels, and energy consumption.",
    price: 599,
    owner: "SmartCityData",
    category: "IoT",
    dataType: "Time Series",
    size: "8.5 GB",
    downloads: 645,
    popularity: 89,
    verified: true,
    createdAt: "2023-09-15",
    previewImage: "/placeholder.svg?height=400&width=600&text=IoT+Data",
    recommended: true,
    recommendationReason:
      "Aligns with your smart city research and contains comprehensive sensor data for urban analytics.",
    matchScore: "92",
  },
  {
    id: "6",
    name: "Satellite Imagery Collection",
    description:
      "High-resolution satellite imagery for environmental monitoring, urban planning, and agricultural analysis with temporal data spanning 5 years.",
    price: 799,
    owner: "EarthObserve",
    category: "Geospatial",
    dataType: "Images",
    size: "12.3 GB",
    downloads: 423,
    popularity: 86,
    verified: true,
    createdAt: "2023-08-10",
    previewImage: "/placeholder.svg?height=400&width=600&text=Satellite+Data",
  },
  {
    id: "7",
    name: "Cryptocurrency Trading Patterns",
    description:
      "Detailed cryptocurrency trading data including price movements, volume, order book depth, and market sentiment indicators.",
    price: 249,
    owner: "CryptoAnalytics",
    category: "Finance",
    dataType: "Time Series",
    size: "1.9 GB",
    downloads: 1876,
    popularity: 95,
    verified: false,
    createdAt: "2023-12-05",
    previewImage: "/placeholder.svg?height=400&width=600&text=Crypto+Data",
  },
  {
    id: "8",
    name: "Autonomous Vehicle Sensor Data",
    description:
      "Comprehensive sensor data from autonomous vehicle testing, including LIDAR, camera, radar, and GPS with annotated objects and scenarios.",
    price: 899,
    owner: "AutoDriveTech",
    category: "Transportation",
    dataType: "Unstructured",
    size: "15.7 GB",
    downloads: 312,
    popularity: 88,
    verified: true,
    createdAt: "2023-07-20",
    previewImage: "/placeholder.svg?height=400&width=600&text=Autonomous+Vehicle+Data",
  },
  {
    id: "9",
    name: "Natural Language Processing Corpus",
    description:
      "Extensive text corpus for NLP training and testing, including multiple languages, domains, and annotation layers for various NLP tasks.",
    price: 399,
    owner: "LanguageAI",
    category: "Text Analytics",
    dataType: "Text",
    size: "4.2 GB",
    downloads: 987,
    popularity: 91,
    verified: true,
    createdAt: "2023-10-15",
    previewImage: "/placeholder.svg?height=400&width=600&text=NLP+Data",
  },
  {
    id: "10",
    name: "Manufacturing Process Optimization",
    description:
      "Industrial manufacturing process data with sensor readings, quality control metrics, and production efficiency indicators for optimization.",
    price: 649,
    owner: "IndustryInsights",
    category: "Manufacturing",
    dataType: "Time Series",
    size: "7.1 GB",
    downloads: 456,
    popularity: 87,
    verified: true,
    createdAt: "2023-09-01",
    previewImage: "/placeholder.svg?height=400&width=600&text=Manufacturing+Data",
  },
  {
    id: "11",
    name: "Consumer Behavior Survey Results",
    description:
      "Comprehensive consumer behavior survey data across demographics, regions, and product categories with trend analysis.",
    price: 199,
    owner: "MarketResearchPro",
    category: "Market Research",
    dataType: "Structured",
    size: "1.3 GB",
    downloads: 1245,
    popularity: 93,
    verified: true,
    createdAt: "2023-11-10",
    previewImage: "/placeholder.svg?height=400&width=600&text=Consumer+Survey+Data",
  },
  {
    id: "12",
    name: "Weather Patterns and Climate Data",
    description:
      "Historical weather and climate data with predictive models, covering global regions with high-resolution temporal and spatial information.",
    price: 349,
    owner: "ClimateAnalytics",
    category: "Environmental",
    dataType: "Time Series",
    size: "6.8 GB",
    downloads: 789,
    popularity: 90,
    verified: true,
    createdAt: "2023-08-25",
    previewImage: "/placeholder.svg?height=400&width=600&text=Climate+Data",
  },
]

